version: '2'
services:
  mysql:
    image: saisriharsha333/mysql
    container_name: mysql-server-800
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=notes
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
    ports:
      - "8082:3306"

  website:
    container_name: php722
    image: saisriharsha333/php_img
    build:
      context: ./
    network_mode: host
    ports:
      - 8000:80
    depends_on:
      - mysql
